### ISSUE TITLE
[Story] I create a story from the "story" view and create a story with the same name in the "sprint" view

### ISSUE THREAD

**Issue by ptrouillard** [amauryleclerc/banana#13]
The story STD_3 is created within the "story" view [OK]
The story STD_3 is not created within the "sprint" view [KO]
Indeed we don't need to create a story alone, but it is always attached to a sprint, even if the sprint is named "backlog PO" for instance...(like in Jira)

**Comment by amauryleclerc** [comment]
You can't create 2 stories with the same name. 
With the issues #12 , you will be able to add a existing story.

**Comment by amauryleclerc** [comment]
I have added an alert for the creation of stories and sprint, for success and error

**Comment by ptrouillard** [comment]
* create the story with the same name : The error message appears but his a little bit "technical" ;-)  
  [KO]  
* add a existing story to a sprint : The message is "undefined added"  [KO] (it is ok for release 1)
* add a story already added to a sprint : The Ok message is "undefined added" and the story has been added [KO] (the story should not have been added)

**Comment by amauryleclerc** [comment]
- I add "setHttpError" in menuService, the 409 status will show "already exist" error
- the "undefined added" error  is solve
- the third point is the issue #16

**Comment by ptrouillard** [comment]
Ok 👍
