### ISSUE TITLE
[Story] Very minor enhancements (marketing)

### ISSUE THREAD

**Issue by ptrouillard** [amauryleclerc/banana#15]
* Change the name in the header "Sprint graph" by a logo
* highlight the view selected in the menu

**Comment by ptrouillard** [comment]
I propose a logo "banana" in the assets/gif dir.
I changed the favicon.ico

**Comment by amauryleclerc** [comment]
I added "banana" in the menu and the icon is now transparent

**Comment by ptrouillard** [comment]
I love it 👍
