### ISSUE TITLE
[BUG] The same story can be added twice in a sprint

### ISSUE THREAD

**Issue by ptrouillard** [amauryleclerc/banana#16]
I did not tested this one at the first time, but it is possible to add a story several times in the sprint

**Comment by amauryleclerc** [comment]
i will change the mantyToMany relation to a oneToMany relation between story and sprint, but it will cause a BREAKING CHANGE

**Comment by amauryleclerc** [comment]
i have replaced the list be a set

**Comment by ptrouillard** [comment]
ça roule 👍
