### ISSUE TITLE
[BUG] In absence view, The form should validate entries in order to block user if he enters incoherent data

### ISSUE THREAD

**Issue by ptrouillard** [amauryleclerc/banana#26]
For instance : 
* when start at noon is checked on the "from date" and the "to date"
* when "from date" > "to date"

**Comment by ptrouillard** [comment]
When I create the absence, the error message is below the popup window. The message is OK, but it is only partially visible

**Comment by amauryleclerc** [comment]
i add <notification></notification> directive

**Comment by amauryleclerc** [comment]
fixed

**Comment by ptrouillard** [comment]
OK
