### ISSUE TITLE
[Story] "Maximize sprint graph" mode

### ISSUE THREAD

**Issue by ptrouillard** [amauryleclerc/banana#5]
In order to display the sprint graph on a screen, we should be able to hide the header and sprint choice combo present in the graph view : move the choice combo in the header and add a "hide" header button

**Comment by amauryleclerc** [comment]
Are they only visible in the graph view?

**Comment by amauryleclerc** [comment]
The graph will be responsive too

**Comment by amauryleclerc** [comment]
I will create a menu service. All controllers will be able to control the menu

**Comment by amauryleclerc** [comment]
@ptrouillard Is it necessary to have a hide button ? Where do you what the hide button ?

**Comment by ptrouillard** [comment]
button...hum not sure indeed
may be a hotkey ?

**Comment by amauryleclerc** [comment]
I added ctrl+up hotkey for fullscreen mode

**Comment by ptrouillard** [comment]
On MacOs, Ctrl+Up is used to minimize the screen. Ctrl+Down should be OK but I don't know if it is used for another function on windows ...

**Comment by amauryleclerc** [comment]
i have replaced "ctrl+up" by "f" like "fullscreen", the function is not executed when the focus is in an input

**Comment by ptrouillard** [comment]
Perfect 👍
