### ISSUE TITLE
I cannot edit the sprint name afterwards

### ISSUE THREAD

**Issue by ptrouillard** [amauryleclerc/banana#6]
The sprint "name" should be editable after the creation in order to fix the name if it is not ok

**Comment by amauryleclerc** [comment]
Do i change the primary key by a UUID ?
for the story name to ?

**Comment by ptrouillard** [comment]
Yes I would set an UUID (not visible in GUI) and a name field (editable)

**Comment by amauryleclerc** [comment]
This issue will cause a breaking change

**Comment by amauryleclerc** [comment]
Solve since f4799cd03aeea72ccfd4c0d87345599e6385c918

**Comment by ptrouillard** [comment]
Banana !
