### ISSUE TITLE
In graph view, the comboBox is not needed

### ISSUE THREAD

**Issue by ptrouillard** [amauryleclerc/banana#7]
The sprint choice does not need to be done in graph view. 
It could be moved in menu bar 

the reason is to have a graph view without any user interaction

**Comment by amauryleclerc** [comment]
I can add a route to /currentGraph.
In this view, the graph is determined by the start and end dates.

**Comment by amauryleclerc** [comment]
Solve since c818516474a51e013288fd61b38152fd35fbdc66

**Comment by ptrouillard** [comment]
Just great 👍
