### ISSUE TITLE
[Technical] l10n

### ISSUE THREAD

**Issue by ptrouillard** [amauryleclerc/banana#8]
application should display text and numbers and dates according to locale set in browser

**Comment by amauryleclerc** [comment]
We can use i18n for the text. The [doc here](https://docs.angularjs.org/guide/i18n)

**Comment by amauryleclerc** [comment]
I have found this [Internationaliser-son-application-avec-AngularJS](https://bigint.fr/blog/2015-04-17/Internationaliser-son-application-avec-AngularJS)

**Comment by amauryleclerc** [comment]
we can use this https://angular-translate.github.io/docs/#/guide/12_asynchronous-loading

**Comment by amauryleclerc** [comment]
I have added two button in the settings view to choose the language

**Comment by ptrouillard** [comment]
OK
